version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://ephratham:ephratham@cluster0.x3irutl.mongodb.net/clinic-dev?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
